version: 2
jobs:
  setup:
    working_directory: /go/src/github.com/segmentio/sarama
    docker:
      - image: segment/circleci-golang:1.10
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: [.]

  test:
    working_directory: /go/src/github.com/segmentio/sarama
    docker:
      - image: segment/circleci-golang:1.10

    resource_class: large
    steps:
      - setup_remote_docker: { reusable: true, docker_layer_caching: true }
      - attach_workspace: { at: . }
      - run: go get -t
      - run:
          name: Vet
          command: make vet
      - run:
          name: Test
          # in order to avoid recreating sarama's vagrant setup, we make the test
          # think it's not running in CI so it skips the kafka integration tests
          command: CI= make test

workflows:
  version: 2
  run:
    jobs:
      - setup:
          filters:
            tags: { only: /.*/ }
      - test:
          requires: [setup]
